# 1 NUMPY PRACTICAL

In [1]:
#importing numpy 
import numpy as np

In [2]:
#creating 1d array
ar = np.array([1,2,3,4,5])

In [3]:
print(ar)

[1 2 3 4 5]


In [4]:
#we can perform element wise operation
print(ar*3)

[ 3  6  9 12 15]


In [5]:
print(ar+5)

[ 6  7  8  9 10]


In [6]:
#for checking the dimensions
print(ar.ndim)

1


In [7]:
#creating the 2d array
ar1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print(ar1.ndim)

2


In [9]:
#for shape
print(ar1.shape)

(3, 4)


In [10]:
#indexing and slicing
print(ar1[0])

[1 2 3 4]


In [11]:
print(ar1[-1])

[ 9 10 11 12]


In [13]:
#for printing the first and the last row
print(ar1[[0,2]])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [14]:
#displaying the sub array
#eg for printing 2 3 6 7
print(ar1[0:2,1:3])

[[2 3]
 [6 7]]


In [18]:
#reshaping of the array
arr = np.arange(1,9)

In [19]:
print(arr)

[1 2 3 4 5 6 7 8]


In [20]:
arr2 = arr.reshape(2,4)

In [21]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
arr3 = arr.reshape(4,2)

In [23]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
#concatination of two arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [25]:
#we use axis =1 for cols and axis = 0 for row
c = np.concatenate((a,b),axis=1)

In [26]:

print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [28]:
d = np.concatenate((a,b),axis=0)

In [29]:
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [30]:
#sorting
ar4 = np.array([[1,2,3],[5,4,3],[9,7,8]])

In [31]:
ar5 = np.sort(ar4,axis=1)#for row wise sort

In [32]:
print(ar5)


[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [33]:
ar6 = np.sort(ar4,axis=0)#for col wise

In [34]:
print(ar6)

[[1 2 3]
 [5 4 3]
 [9 7 8]]


In [35]:
#putting conditions
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([9,10,11,12,13,14,15,16])

In [36]:
#to find all the values > 6
print(a[a>6])

[7 8]


In [37]:
print(b[b>6])

[ 9 10 11 12 13 14 15 16]


In [38]:
#for finding the common elemennts in both a and b
c = set(a) & set(b)

In [39]:
print(list(c))

[]


In [40]:
#it means no element is common

In [41]:
array = np.array([1,2,3,1,3,5,6,2,7,8,9,1])

In [44]:
print(np.unique(array))

[1 2 3 5 6 7 8 9]


In [47]:
# creating an array with 0s
zero = np.zeros((4,5))

In [48]:
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
ones = np.ones((4,5))

In [50]:
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
arr8 = np.array([1,2,3,4,5,6,7,8,9])

In [52]:
print(np.sum(arr8))

45


In [53]:
print(np.mean(arr8))

5.0


In [54]:
#matrix multiplication 
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [55]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [57]:
print(np.matmul(a,b))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
